-- Step 1: Enable RLS on all tables
-- Run this first in Supabase SQL Editor

ALTER TABLE "Account" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VerificationToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FormSubmission" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EmailInbox" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EmailThread" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Email" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Note" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Task" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DJ" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Musician" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BookingStaffAssignment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EmailTemplate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FreelanceCrew" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NewEnquiry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CommsLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CartItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Cart" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Staff_Settings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Booking" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HireItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HireOrder" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HireOrderItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VenueAsset" ENABLE ROW LEVEL SECURITY;
