/**
 * Safe Booking select for use when DB may not have services, upsellItems, or termsAcceptedVersion.
 * Use in admin (and client) APIs to avoid "The column (not available) does not exist" until migrations are run.
 * Call addBookingFallbacks() on each booking before passing to UI/transformBooking.
 */
export const SAFE_BOOKING_SCALARS = {
  id: true,
  userId: true,
  name: true,
  displayName: true,
  email: true,
  phoneAreaCode: true,
  phoneNumber: true,
  clientAddress: true,
  clientAddress2: true,
  clientTown: true,
  clientCounty: true,
  clientPostcode: true,
  eventType: true,
  eventDate: true,
  venueName: true,
  venueContact: true,
  venueAddress: true,
  venueAddress2: true,
  venueTown: true,
  venueCounty: true,
  venuePostcode: true,
  venuePhoneAreaCode: true,
  venuePhoneNumber: true,
  ceremonyTime: true,
  djArrivalTime: true,
  djStartTime: true,
  djFinishTime: true,
  djSetupLocation: true,
  djParking: true,
  soundLimiter: true,
  venueIsPrivateHouse: true,
  venueWhat3Words: true,
  venueLoadInNotes: true,
  numberOfGuests: true,
  message: true,
  budget: true,
  status: true,
  contactPreference: true,
  finalBalance: true,
  paymentMethod: true,
  paymentPayerName: true,
  termsAccepted: true,
  termsAcceptedAt: true,
  termsAcceptedByUserId: true,
  completedTasks: true,
  emailsSent: true,
  lastEmailSentAt: true,
  musicNotesToDJ: true,
  musicNotesToStylish: true,
  firstDance: true,
  lastSong: true,
  musicDislikes: true,
  musicRequests: true,
  musicFileUrl: true,
  portalHeroImageUrl: true,
  createdAt: true,
  updatedAt: true,
  archivedAt: true,
  archivedBy: true,
  preferredDJ: true,
  priority: true,
  adminNotes: true,
  authorizedSenders: true,
  bookingReference: true,
  conflictResolvedAt: true,
  conflictStatus: true,
  depositReceived: true,
  depositReceivedManual: true,
  bookingFee: true,
  confirmedViaBookFromQuote: true,
  depositInvoiceSentAt: true,
  depositPaidClickedAt: true,
  djWorksheetApproved: true,
  djWorksheetApprovedManual: true,
  feeBreakdown: true,
  finalDetailsConfirmed: true,
  finalDetailsConfirmedManual: true,
  flaggedFor: true,
  handoffNote: true,
  handoffStatus: true,
  isTechReady: true,
  overrideReason: true,
  purgeAt: true,
  rescuedAt: true,
  selectedTemplate: true,
  talentStatus: true,
  taxInclusive: true,
  taxRate: true,
  venueFingerprint: true,
  portalToken: true,
  guestRequestToken: true,
  guestRequestsEnabled: true,
  assignedTo: true,
} as const;

/** Add fallbacks for columns that may not exist in DB (services, upsellItems, termsAcceptedVersion). */
export function addBookingFallbacks<T extends Record<string, unknown>>(booking: T): T & { services: string[]; upsellItems: string[]; termsAcceptedVersion: string | null } {
  return {
    ...booking,
    services: Array.isArray((booking as any).services) ? (booking as any).services : [],
    upsellItems: Array.isArray((booking as any).upsellItems) ? (booking as any).upsellItems : [],
    termsAcceptedVersion: (booking as any).termsAcceptedVersion ?? null,
  } as T & { services: string[]; upsellItems: string[]; termsAcceptedVersion: string | null };
}
