#!/bin/bash
# Audit all venue URLs for 404 or connection errors
# Usage: ./scripts/audit-venue-urls.sh

URLS=(
"https://almonrybarnsomerset.com/"
"https://atthechapel.co.uk/"
"https://aynhoepark.co.uk/"
"https://chigwellhall.com/"
"https://mellsbarn.org/"
"https://mordenhall.com/"
"https://quendonhall.co.uk/"
"https://rothbar.co.uk/"
"https://sessionsartsclub.com/"
"https://www.1lombardstreet.com/"
"https://www.assemblyroomsbath.co.uk/"
"https://www.athelhampton.co.uk/"
"https://www.bailbrookhouse.co.uk/"
"https://www.barnsleyhouse.com/"
"https://www.berkeley-castle.com/"
"https://www.bixmanor.co.uk/"
"https://www.boconnoc.com/"
"https://www.brooklandsmuseum.com/"
"https://www.brymptonhouse.co.uk/"
"https://www.cadhay.co.uk/"
"https://www.calcot.co/"
"https://www.cardiffcastle.com/"
"https://www.cardiffcityhall.com/"
"https://www.comptonhall.co.uk/"
"https://www.coombelodge.co.uk/"
"https://www.cowleymanor.com/"
"https://www.crippsbarn.co.uk/"
"https://www.cutteridgebarns.co.uk/"
"https://www.danesfieldhouse.co.uk/"
"https://www.denefarm.co.uk/"
"https://www.dorfoldestate.com/"
"https://www.drakeandmorgan.co.uk/devonshire-terrace/"
"https://www.eastnorcastle.com/"
"https://www.elmorecourt.com/"
"https://www.firmdalehotels.com/hotels/london/ham-yard-hotel/"
"https://www.friarscourt.co.uk/"
"https://www.gantsmill.co.uk/"
"https://www.glastonburyfestivals.co.uk/"
"https://www.goodwood.com/"
"https://www.greattythebarn.co.uk/"
"https://www.hamptoncourthouse.co.uk/"
"https://www.hassophall.co.uk/"
"https://www.hestercombe.com/"
"https://www.homewoodpark.co.uk/"
"https://www.hotelduvin.com/locations/poole/"
"https://www.huntshamcourt.co.uk/"
"https://www.kingscotebarn.co.uk/"
"https://www.kingscotehouse.co.uk/"
"https://www.lantallack.co.uk/"
"https://www.letchworthcentre.org/"
"https://www.lulworth.com/"
"https://www.manorhousecastlecombe.co.uk/"
"https://www.mellsmanor.co.uk/"
"https://www.metropolitanlondon.com/"
"https://www.northcadburycourt.com/"
"https://www.northovermanor.co.uk/"
"https://www.orchardleigh.com/"
"https://www.oxfordtownhall.co.uk/"
"https://www.parklandsquendonhall.co.uk/"
"https://www.pembroke-lodge.co.uk/"
"https://www.pencarrow.co.uk/"
"https://www.pennsylvaniacastle.co.uk/"
"https://www.pentillie.co.uk/"
"https://www.polurrianbay.com/"
"https://www.priorybarn.com/"
"https://www.pristonmill.co.uk/"
"https://www.pythousekitchengarden.co.uk/"
"https://www.qmul.ac.uk/"
"https://www.revolution-bars.co.uk/"
"https://www.rhinefieldhouse.co.uk/"
"https://www.rivervalebarn.co.uk/"
"https://www.rlyc.org.uk/"
"https://www.rockinghamcastle.com/"
"https://www.russetscountryhouse.co.uk/"
"https://www.sheldonmanor.co.uk/"
"https://www.shilstonemanor.co.uk/"
"https://www.sohohouse.com/houses/babington-house"
"https://www.sohohouse.com/houses/soho-farmhouse"
"https://www.stgeorgesbristol.co.uk/"
"https://www.stokepark.com/"
"https://www.stokeplace.com/"
"https://www.stonebarnaldsworth.co.uk/"
"https://www.swallowsnestbarn.co.uk/"
"https://www.syrencot.co.uk/"
"https://www.talljohnshouse.com/"
"https://www.thamesrc.co.uk/"
"https://www.thebingham.co.uk/"
"https://www.thebrewerylondon.co.uk/"
"https://www.thecliftonclub.co.uk/"
"https://www.thegatheringbarn.co.uk/"
"https://www.thehoste.com/"
"https://www.theinandout.co.uk/"
"https://www.thejamfactoryoxford.co.uk/"
"https://www.themayfairhotel.co.uk/"
"https://www.thenave.co.uk/"
"https://www.thenewtinsomerset.com/"
"https://www.thepaintworks.co.uk/"
"https://www.thepighotel.com/bath"
"https://www.theredbarnblindleyheath.co.uk/"
"https://www.thevictorianbarn.co.uk/"
"https://www.thewellingtonarms.com/"
"https://www.tisbury.org.uk/"
"https://www.townhallhotel.com/"
"https://www.tresanton.com/"
"https://www.uggeshallhall.co.uk/"
"https://www.warwick-castle.com/"
"https://www.wellbarn.co.uk/"
"https://www.wentworthestate.org.uk/"
"https://www.wickfarm.co.uk/"
"https://www.yarlingtonhouse.co.uk/"
"https://yacht-club-monaco.mc/en/home/"
)

FAILED=()
OK=0
TOTAL=${#URLS[@]}

for url in "${URLS[@]}"; do
  code=$(curl -s -o /dev/null -w "%{http_code}" -L --max-time 10 "$url" 2>/dev/null || echo "000")
  if [[ "$code" == "200" ]] || [[ "$code" =~ ^3 ]]; then
    ((OK++))
  else
    FAILED+=("$code $url")
  fi
  echo "$code $url"
done

echo ""
echo "=== Summary ==="
echo "OK (200/3xx): $OK/$TOTAL"
echo "Failed: ${#FAILED[@]}"
if [[ ${#FAILED[@]} -gt 0 ]]; then
  echo ""
  echo "Failed URLs:"
  printf '%s\n' "${FAILED[@]}"
fi
